name = "Jakira Modpack"
author = "Kira"
version = "1.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d9bd9283c25c4df29446bb2ac679e9f2ea957582818988b3daf7ebc7c1ea1ebc"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
