name = "Jakira Modpack"
author = "Kira"
version = "1.3.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fda82477f800beaa5526071d6f096cfc60fc1c2754d5ecbeef4f36738b0c5fdc"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
