name = "Jakira Modpack"
author = "Kira"
version = "1.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fafa3d915ee2dc0b5ae93906667581afc0f69a811230ef790f2d6b55b13045d8"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
