name = "Jakira Modpack"
author = "Kira"
version = "1.3.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b0a3d85181395c21218579dfb5b8b88aa14065fef9c30a2a05738a63ed20b9db"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
