name = "Jakira Modpack"
author = "Kira"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fca872391a7a6a04850e8b0a7801c74a1375bdba39bbb90f1081cc1f90fd9914"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
